name: Publish to pypi
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

    paths:
      - "rbrapi/__init__.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build rbrapi
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          python -m pip install build
          python -m build

      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
